// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOcZVcUoBMabMVvS_PT10_5ai8_MnMTg',
    appId: '1:263066582758:web:ffef15fe2f2d322e4fc527',
    messagingSenderId: '263066582758',
    projectId: 'shg2022-ee3eb',
    authDomain: 'shg2022-ee3eb.firebaseapp.com',
    storageBucket: 'shg2022-ee3eb.appspot.com',
    measurementId: 'G-6GPV6GBYKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZWoo3Pqqm62rBXNoc0tsZcc8l3BeQrQ',
    appId: '1:263066582758:android:80c11f5af55f23914fc527',
    messagingSenderId: '263066582758',
    projectId: 'shg2022-ee3eb',
    storageBucket: 'shg2022-ee3eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ0qrpFKVQVwaGvwgG9d7w1MwAJm3q8Ig',
    appId: '1:263066582758:ios:548f6c79e0c75bb04fc527',
    messagingSenderId: '263066582758',
    projectId: 'shg2022-ee3eb',
    storageBucket: 'shg2022-ee3eb.appspot.com',
    iosClientId: '263066582758-gljvl1md9ptqkear7ti1ah8kqtsua392.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ0qrpFKVQVwaGvwgG9d7w1MwAJm3q8Ig',
    appId: '1:263066582758:ios:548f6c79e0c75bb04fc527',
    messagingSenderId: '263066582758',
    projectId: 'shg2022-ee3eb',
    storageBucket: 'shg2022-ee3eb.appspot.com',
    iosClientId: '263066582758-gljvl1md9ptqkear7ti1ah8kqtsua392.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfHelp',
  );
}
